### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by adelin-b** [richardwesthaver/org-notion#2]
Hello, 
I am interrested in this package however the description of the usage is a bit light. I made my own attempt a while ago to replicate notion inside orgmode and sync the changes. And I wonder if this is what is intended with this package or if its just an api wrapper.

Here is my user path so far.

- install the package
- call notion-token, set email, set token
- create a notion.org file
- enable org-notion mode
- call org-notion-cull shortcut
- nothing happen.

Maybe a few sample on how to use the commands would be good ?

**Comment by richardwesthaver** [comment]
hey there @adelin-b, org-notion isn't ready for prime time yet - org-notion-pull/push are placeholders. the bulk of work to be done involves implementing org-notion-from-org and org-notion-to-org methods for the eieio classes using org-element. I have been busy with work and unable to put in the hours to make significant progress but hope to soon!

**Comment by richardwesthaver** [comment]
@adelin-b I will close this out, but stay tuned for additional updates to the readme.

on the topic of intended use-cases:
my idea is to treat Notion as my 'mobile org' solution and as a frontend for collaboration.

Typical workflow would be taking notes in org-mode, evaluating `org-notion-push`, and then using Notion on my phone to read and update content. When I come back to my computer I run `org-notion-pull` to sync and repeat the process.

Sometimes I also make project documents and roadmaps which I want to work on with multiple people with edit access -- Notion is very good at this and org-mode is not, so this package would make that workflow seamless.
